# Generated by Django 5.0.7 on 2024-11-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('camion', 'Camión'), ('camioneta', 'Camioneta'), ('motoneta', 'Motoneta'), ('furgon', 'Furgón')], max_length=50)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('ubicacion_actual', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=50)),
                ('kilometraje', models.PositiveIntegerField()),
                ('conductor', models.CharField(max_length=100)),
                ('mantenimiento_ruta_actual', models.CharField(max_length=255)),
                ('ruta', models.CharField(max_length=255)),
                ('reporte', models.CharField(max_length=255)),
                ('sensor', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
            ],
        ),
    ]
