# Generated by Django 5.0.7 on 2024-11-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_remove_vehiculo_ubicacion_alter_vehiculo_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(default='activo', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='kilometraje',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='mantenimiento_ruta_actual',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='reporte',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='ruta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='sensor',
            field=models.CharField(default='activo', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='ubicacion_actual',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
